version: 0.0
os: linux

files:
  - source: /
    destination: /tmp/codedeploy-deploy
  
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
    
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: validate_service.sh
      timeout: 60
      runas: root